name:                xml-typelift
version:             0.0.1
synopsis:            Converting XML Schema to Haskell datatype
description: |
    Generates datatype declarations and parser/prettyprinter
    for it from XML Schema.
    .
    Addresses handling of large documents with large schemas, like Office Open XML.
homepage:            https://github.com/DataHaskell/xml-typelift
license:             BSD3
license-file:        LICENSE
stability:           stable
author:              Michal Gajda
maintainer:          dataopt@example.com
copyright:           Copyright by Michal Gajda 2018
category:            Data, Tools, Development
build-type:          Simple
extra-source-files:
  - README.md
  - changelog.md
  - test/person.xsd
bug-reports:         https://github.com/DataHaskell/xml-typelift/issues
github: DataHaskell/xml-typelift

ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - containers
  - deepseq
  - filepath
  - haskell-src-match
  - interpolatedstring-perl6
  - iso8601-duration # for testing!
  - lens
  - mtl
  - pretty-simple
  - template-haskell
  - uniplate
  - xeno

flags:
  use-parser2:
    description: Add Parser2 to benchmarks
    manual: true
    default: false

library:
  source-dirs:
    - lib
  exposed-modules:
    - FromXML

executables:
  xml-typelift-cli:
    main: Cli.hs
    source-dirs:
      - src
      - app
      - bench
    dependencies:
      - optparse-applicative
      - xml-typelift
  mkxml:
    main: Main.hs
    source-dirs:
      - lib
      - bench/proto/mkxml
      - bench/proto/lib
    dependencies:
      - xml-typelift
      - QuickCheck
      - generic-arbitrary
      - perfect-vector-shuffle
      - scientific
      - time
      - vector
    ghc-options: -O2
  parser5:
    main: Main.hs
    source-dirs:
      - lib
      - bench/proto/lib
      - bench/proto/main/parser5
      - bench/proto/parsers
      - xeno-proposal
    dependencies:
      - ghc-prim
      - megaparsec
      - pretty
      - xml-typelift
      - scientific
      - time
      - vector
    ghc-options: -O2
  parser6:
    main: Main.hs
    source-dirs:
      - lib
      - bench/proto/lib
      - bench/proto/main/parser6
      - bench/proto/parsers
      - xeno-proposal
    dependencies:
      - ghc-prim
      - megaparsec
      - pretty
      - xml-typelift
      - scientific
      - time
      - vector
    ghc-options: -O2

tests:
  unit-tests:
    source-dirs:
      - test
      - src
    main: Tests.hs
    dependencies:
      - hspec
      - xml-typelift
      - temporary
      - process
      - template-haskell

benchmarks:
  speed:
    source-dirs:
      - bench/speed
      - bench
      - src
    main: Main.hs
    dependencies:
      - criterion >= 1.5.0.0
      - weigh
      - xml-typelift
  memory:
    source-dirs:
      - bench/memory
      - bench
      - src
    main: Main.hs
    dependencies:
      - criterion
      - weigh
      - xml-typelift
  generated-parsers-speed:
    main: Main.hs
    source-dirs:
      - lib
      - src
      - xeno-proposal
      - bench/proto
      - bench/proto/lib
      - bench/proto/parsers
      - bench/proto/speed
    dependencies:
      - criterion
      - ghc-prim
      - megaparsec
      - scientific
      - time
      - vector
      - xml-typelift
    ghc-options: -O2 -rtsopts
    when:
      - condition: flag(use-parser2)
        cpp-options: -DBENCH_USE_PARSER2
  generated-parsers-memory:
    main: Main.hs
    source-dirs:
      - lib
      - src
      - xeno-proposal
      - bench/proto
      - bench/proto/lib
      - bench/proto/parsers
      - bench/proto/memory
    dependencies:
      - ghc-prim
      - megaparsec
      - mmap
      - scientific
      - time
      - vector
      - weigh
      - xml-typelift
    ghc-options: -O2 -rtsopts "-with-rtsopts=-H1G"
    when:
      - condition: flag(use-parser2)
        cpp-options: -DBENCH_USE_PARSER2
